In [17]:
import numpy as np
from math import sin,cos,pi
from funcoesTermosol import *

In [31]:
numNo,matrixNo,numMemb,matrixInc,numCar,vetorFor,numRes,vetorRes = importa("entrada.xlsx")
print(matrixInc)

[[1.0e+00 2.0e+00 2.1e+11 2.0e-04]
 [2.0e+00 3.0e+00 2.1e+11 2.0e-04]
 [3.0e+00 1.0e+00 2.1e+11 2.0e-04]]


In [28]:
class no:
    def __init__(self, num, ponto):
        self.x = ponto[0]
        self.y = ponto[1]
        self.num = num
        self.graux = num*2 - 1
        self.grauy = num*2

In [33]:
class barra:
    def __init__(self,E,A, no1, no2):
        self.E = E
        self.A = A
        self.L = ((no2.x - no1.x)**2+(no2.y - no1.y)**2)**0.5
        s = (no2.y - no1.y)/self.L
        c = (no2.x - no1.x)/self.L
        self.matrix = (self.E*self.A/self.L)*np.array([[c**2,c*s,-c**2,-c*s],
                                                       [c*s,s**2,-c*s,-s**2],
                                                       [-c**2,-c*s,c**2,c*s],
                                                       [-c*s,-s**2,c*s,s**2]])
        self.listagraus = [no1.graux, no1.grauy, no2.graux, no2.grauy]


In [21]:
def simplificaGeral(matrix, n):
    newMatrix = np.delete(matrix, (n), axis=0)
    newMatrix = np.delete(newMatrix, (n), axis=1)
    return newMatrix

def simplificaSimples(matrix, n):
    newMatrix = np.delete(matrix, (n), axis=0)
    return newMatrix

In [8]:
# def matrixKg(listaMatrix):
#     n = len(listaMatrix)
#     zero = np.zeros((n+1,n+1))
#     for i,mat in enumerate(listaMatrix):
#         zero[i][i] = mat[0][0]
#         zero[i][i+1] = mat[0][1]
#         zero[i+1][i] = mat[1][0]
#         zero[i+1][i+1] = mat[1][1]
#     return zero
    

In [30]:
listaNo = []
for i in range(numNo):
    n = no(i+1, [matrixNo[0][i],matrixNo[1][i]])
    listaNo.append(n)


2
4
6


In [37]:
listaBarra = []
for i in range(len(matrixInc)):
    b = barra(matrixInc[i][2],matrixInc[i][3],listaNo[int(matrixInc[i][0]) - 1],listaNo[int(matrixInc[i][1]) - 1])
    listaBarra.append(b)
    print(b.listagraus)

[1, 2, 3, 4]
[3, 4, 5, 6]
[5, 6, 1, 2]


In [10]:
listaBarra = [barra1,barra2]
listaMatrix = [bar.matrix for bar in listaBarra]

In [ ]:
cos(pi/2)